module.exports = {
    name: 'roll',
    category: 'fun',
    description: 'Tire un nombre au hasard',
    run: async (bot,message, args) => {

        let choices = [
            "J'ai tirez le nombre **1**! 🎲",
            "J'ai tirez le nombre **2**! 🎲",
            "J'ai tirez le nombre **3**! 🎲",
            "J'ai tirez le nombre **4**! 🎲",
            "J'ai tirez le nombre **5**! 🎲",
            "J'ai tirez le nombre **6**! 🎲",
            "J'ai tirez le nombre **7**! 🎲",
            "J'ai tirez le nombre **8**! 🎲",
            "J'ai tirez le nombre **9**! 🎲",
            "J'ai tirez le nombre **10**! 🎲",
            "J'ai tirez le nombre **11**! 🎲",
            "J'ai tirez le nombre **12**! 🎲",
            "J'ai tirez le nombre **13**! 🎲",
            "J'ai tirez le nombre **14**! 🎲",
            "J'ai tirez le nombre **15**! 🎲",
            "J'ai tirez le nombre **16**! 🎲",
            "J'ai tirez le nombre **17**! 🎲",
            "J'ai tirez le nombre **18**! 🎲",
            "J'ai tirez le nombre **19**! 🎲",
            "J'ai tirez le nombre **20**! 🎲",
            "J'ai tirez le nombre **21**! 🎲",
            "J'ai tirez le nombre **22**! 🎲",
            "J'ai tirez le nombre **23**! 🎲",
            "J'ai tirez le nombre **24**! 🎲",
            "J'ai tirez le nombre **25**! 🎲",
            "J'ai tirez le nombre **26**! 🎲",
            "J'ai tirez le nombre **27**! 🎲",
            "J'ai tirez le nombre **28**! 🎲",
            "J'ai tirez le nombre **29**! 🎲",
            "J'ai tirez le nombre **30**! 🎲",
            "J'ai tirez le nombre **31**! 🎲",
            "J'ai tirez le nombre **32**! 🎲",
            "J'ai tirez le nombre **33**! 🎲",
            "J'ai tirez le nombre **34**! 🎲",
            "J'ai tirez le nombre **35**! 🎲",
            "J'ai tirez le nombre **36**! 🎲",
            "J'ai tirez le nombre **37**! 🎲",
            "J'ai tirez le nombre **38**! 🎲",
            "J'ai tirez le nombre **39**! 🎲",
            "J'ai tirez le nombre **40**! 🎲",
            "J'ai tirez le nombre **41**! 🎲",
            "J'ai tirez le nombre **42**! 🎲",
            "J'ai tirez le nombre **43**! 🎲",
            "J'ai tirez le nombre **44**! 🎲",
            "J'ai tirez le nombre **45**! 🎲",
            "J'ai tirez le nombre **46**! 🎲",
            "J'ai tirez le nombre **47**! 🎲",
            "J'ai tirez le nombre **48**! 🎲",
            "J'ai tirez le nombre **49**! 🎲",
            "J'ai tirez le nombre **50**! 🎲",
            "J'ai tirez le nombre **51**! 🎲",
            "J'ai tirez le nombre **52**! 🎲",
            "J'ai tirez le nombre **53**! 🎲",
            "J'ai tirez le nombre **54**! 🎲",
            "J'ai tirez le nombre **55**! 🎲",
            "J'ai tirez le nombre **56**! 🎲",
            "J'ai tirez le nombre **57**! 🎲",
            "J'ai tirez le nombre **58**! 🎲",
            "J'ai tirez le nombre **59**! 🎲",
            "J'ai tirez le nombre **60**! 🎲",
            "J'ai tirez le nombre **61**! 🎲",
            "J'ai tirez le nombre **62**! 🎲",
            "J'ai tirez le nombre **63**! 🎲",
            "J'ai tirez le nombre **64**! 🎲",
            "J'ai tirez le nombre **65**! 🎲",
            "J'ai tirez le nombre **66**! 🎲",
            "J'ai tirez le nombre **67**! 🎲",
            "J'ai tirez le nombre **68**! 🎲",
            "J'ai tirez le nombre **69**! 🎲",
            "J'ai tirez le nombre **70**! 🎲",
            "J'ai tirez le nombre **71**! 🎲",
            "J'ai tirez le nombre **72**! 🎲",
            "J'ai tirez le nombre **73**! 🎲",
            "J'ai tirez le nombre **74**! 🎲",
            "J'ai tirez le nombre **75**! 🎲",
            "J'ai tirez le nombre **76**! 🎲",
            "J'ai tirez le nombre **77**! 🎲",
            "J'ai tirez le nombre **78**! 🎲",
            "J'ai tirez le nombre **79**! 🎲",
            "J'ai tirez le nombre **80**! 🎲",
            "J'ai tirez le nombre **81**! 🎲",
            "J'ai tirez le nombre **82**! 🎲",
            "J'ai tirez le nombre **83**! 🎲",
            "J'ai tirez le nombre **84**! 🎲",
            "J'ai tirez le nombre **85**! 🎲",
            "J'ai tirez le nombre **86**! 🎲",
            "J'ai tirez le nombre **87**! 🎲",
            "J'ai tirez le nombre **88**! 🎲",
            "J'ai tirez le nombre **89**! 🎲",
            "J'ai tirez le nombre **90**! 🎲",
            "J'ai tirez le nombre **91**! 🎲",
            "J'ai tirez le nombre **92**! 🎲",
            "J'ai tirez le nombre **93**! 🎲",
            "J'ai tirez le nombre **94**! 🎲",
            "J'ai tirez le nombre **95**! 🎲",
            "J'ai tirez le nombre **96**! 🎲",
            "J'ai tirez le nombre **97**! 🎲",
            "J'ai tirez le nombre **98**! 🎲",
            "J'ai tirez le nombre **99**! 🎲",
            "J'ai tirez le nombre **100**! 🎲"

        ];

        let output =
        choices[Math.floor(Math.random()*choices.length)]
        message.reply(`${output}`)
    }
}
module.exports.help = {
    name: "roll"
}